name: GitHub Actions Demo

run-name: CI

on: push

jobs:   
  publish:
    runs-on: ubuntu-latest
    steps:
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        -
          name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-test-project:latest

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
        - name: install ssh keys
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

        - name: connect and pull
          run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.DIRECTORY }} && docker compose pull && docker compose up -d && docker image prune -f && exit"
        - name: cleanup
          run: rm -rf ~/.ssh
